name: html5_demo
description: HTML wrapper library for DDC and JS
version: 0.0.1
author: Vittorio Ballestra <vittorio.ballestra@gmail.com>
homepage: https://github.com/dam0vm3nt/html
environment:
    sdk: ">=1.8.0 <2.0.0"
dependencies:
  html5: ^0.0.4
  js: ^0.6.1
#dependency_overrides:
# html5:
#   path: /home/vittorio/Develop/dart/html_lib_bazel
